from autoencoder import JSCC_Autoencoder
import torch
import matplotlib.pyplot as plt
import os
import numpy as np
from canopyPlots import createCHM

RESOLUTION = 2
FACTOR = 3
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# DEVICE = "cpu"
EPSILON = 1e-8

CONFIG = {
    "input_shape": (128, 32, 16),
    "base_channels": 32,
    "num_res_blocks": 6,
    "num_res_blocks_lidar": 1,
    "channel_snr_db_range": (0, 20),
    "compression_ratio": 8,
    "learning_rate": 1e-4,
    "batch_size": 64,
    "num_epochs": 200,
    "results_dir": "./autoencoder_lambda",
}

model = JSCC_Autoencoder(CONFIG)
resume_checkpoint_path = os.path.join(
    CONFIG["results_dir"],
    f"best_val_model_compression_{CONFIG['compression_ratio']}.pt"
)

if os.path.exists(resume_checkpoint_path):
    print(f"Loading checkpoint: {resume_checkpoint_path}")
    checkpoint = torch.load(resume_checkpoint_path, map_location="cpu")

    target_model = model
    target_model.load_state_dict(checkpoint["model_state_dict"])

    print(f"Loaded epoch {checkpoint.get('epoch', 'N/A')} | best_val_loss={checkpoint.get('best_val_loss', 'N/A')}")
else:
    print(f"No checkpoint found at: {resume_checkpoint_path}")

from datasets import load_dataset
import torch

from forward_model import LidarForwardImagingModel  # or your actual import path (check scripts folder in this repo)

# Load dataset
ds = load_dataset("anfera236/HHDC", split="test")
ds.set_format(type="torch", columns=["cube"])
sample = ds[2]
# High-res “clean” HHDC: [bins, H, W]
clean = sample["cube"]

# Instantiate the LiDAR forward model (use your actual parameters)
forward_model = LidarForwardImagingModel(
    output_res_m=(3.0, 6.0),
    footprint_diameter_m=10.0,
    b=0.1, # set to zero for no background photons
    eta=0.5, # set to zero for no Gaussian noise
    ref_altitude=500.0,
    ref_photon_count=20.0,
)

forward_model.to(DEVICE)
model.to(DEVICE)

def load_and_preprocess_data():
    """Load, crop, and normalize the ground truth voxel cube."""
    ground_truth = torch.from_numpy(np.swapaxes(np.load('TestCube/southeast.npy'), -1, -2)).float().to(DEVICE)
    ground_truth = ground_truth[:, :(96 // RESOLUTION) * FACTOR, :(96 // RESOLUTION) * FACTOR]
    ground_truth = ground_truth / (ground_truth.max(dim=0)[0] + EPSILON)
    ground_truth = torch.roll(ground_truth, shifts=20, dims=0)
    ground_truth = torch.flip(ground_truth, dims=[1, 2])
    return ground_truth
    
clean = load_and_preprocess_data()

# Low-res noisy measurement generated by the forward model: [bins, H_low, W_low]
noisy, lambda_val = forward_model(clean.to(DEVICE))
noisy = noisy.unsqueeze(0).unsqueeze(0)

reconstruction = model(noisy, torch.tensor([5.0]).to(DEVICE)).detach().squeeze()
np.save("./TestCube/reconstructionFL.npy", reconstruction.cpu().numpy())
noisy = noisy.squeeze()
lambda_val = lambda_val.squeeze()

mse_tensor = torch.mean((reconstruction - lambda_val) ** 2)

print(f"MSE between reconstruction and GT: {mse_tensor.item():.6f}")

if mse_tensor.item() == 0:
    psnr = float('inf')
else:
    max_val = lambda_val.max()
    psnr = 10 * torch.log10((max_val ** 2) / mse_tensor).item()

print(f"PSNR between reconstruction and GT: {psnr:.2f} dB")

fig, ax = plt.subplots(2, 3, figsize=(12, 6))

# Row 2: waveforms in order -> noisy, reconstruction, lambda
ax[1, 0].plot(noisy.cpu().numpy()[:, 0, 0], label="Noisy waveform")
ax[1, 0].set_title("Noisy waveform")

ax[1, 1].plot(reconstruction.cpu().numpy()[:, 0, 0], label="Reconstructed waveform")
ax[1, 1].set_title("Reconstructed waveform")

ax[1, 2].plot(lambda_val.cpu().numpy()[:, 0, 0], label="GT")
ax[1, 2].set_title("GT waveform")

# Row 1: images in order -> noisy, reconstruction, lambda
# reconstruction = reconstruction - reconstruction.min(0)[0]
# lambda_val = lambda_val - lambda_val.min(0)[0]

# clean = clean / (clean.max(0, keepdim=True)[0] + 1e-8) # Normalize clean data for better visualization
# noisy = noisy / (noisy.max(0, keepdim=True)[0] + 1e-8) # Normalize noisy data for better visualization
# lambda_val = lambda_val / (lambda_val.max(0, keepdim=True)[0] + 1e-8) # Normalize lambda values for better visualization
# reconstruction = reconstruction / (reconstruction.max(0, keepdim=True)[0] + 1e-8) # Normalize reconstruction for better visualization

im1 = ax[0, 0].imshow(noisy.cpu().numpy()[::-1, -1, :], aspect="auto", cmap="gray_r",interpolation="nearest")
ax[0, 0].set_title("Noisy Measurement")
fig.colorbar(im1, ax=ax[0, 0], fraction=0.046, pad=0.04)

im2 = ax[0, 1].imshow(reconstruction.cpu().numpy()[::-1, -1, :], aspect="auto", cmap="gray_r",interpolation="nearest")
ax[0, 1].set_title("Reconstruction")
fig.colorbar(im2, ax=ax[0, 1], fraction=0.046, pad=0.04)

im3 = ax[0, 2].imshow(lambda_val.squeeze().cpu().numpy()[::-1, -1, :], aspect="auto", cmap="gray_r",interpolation="nearest")
ax[0, 2].set_title("GT")
fig.colorbar(im3, ax=ax[0, 2], fraction=0.046, pad=0.04)

plt.tight_layout()
plt.show()

fig, ax = plt.subplots(1, 3, figsize=(15, 5))
chm_gt = createCHM(clean.cpu().numpy() - 0.15)[0]
chm_recon = createCHM(reconstruction.cpu().numpy() - 0.15)[0]
chm_noisy = createCHM(noisy.cpu().numpy() - 0.15)[0]
ax[0].imshow(chm_noisy, cmap="viridis",aspect="auto",interpolation="nearest")
ax[0].set_title("CHM from Noisy Measurement")
ax[1].imshow(chm_recon, cmap="viridis",aspect="auto",interpolation="nearest")
ax[1].set_title("CHM from Reconstruction")
ax[2].imshow(chm_gt, cmap="viridis",aspect="auto",interpolation="nearest")
ax[2].set_title("CHM from GT")
plt.tight_layout()
plt.show()